# Generated by Django 5.1.6 on 2025-02-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home', 'Главная страница'), ('about', 'О нас'), ('archive', 'Архив')], default='home', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'date'],
            },
        ),
    ]
